;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   周六 2月 27 2016
; Processor: 80C52
; Compiler:  ASEM-51 (Proteus)
;====================================================================

$NOMOD51
$INCLUDE (80C52.MCU)

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      org   0000h
      jmp   Start

;====================================================================
; CODE SEGMENT
;====================================================================

      org   0100h
START:	
	LCALL INITSPACE		;初始化设备
	LCALL SCANNING		;扫描程序
	LCALL INITSERIAL	;串行输入输出

	MOV A,R3		;
	XRL A,09
	JNZ START
	JMP START
	
	
INITSERIAL:
        MOV SCON,#40H		
	MOV TMOD,#20H
	MOV TH1,#0FDH
	MOV TL2,#0FDH
	SETB TR1
	SETB REN
	JNB RI,$
	CLR RI
	MOV A,SBUF

	XRL A,#7DH
	JZ SENDDATA
	RET

SENDDATA:
	MOV R0,#40H
	MOV R1,#8
SUBSEND:
	MOV A,@R0
	INC R0
	MOV SBUF,A
	JNB TI,$
	CLR TI
	DJNZ R1,SUBSEND
	RET
	
INITSPACE:
        MOV 40H,#00H  ;在RAM中定义8个存储单元用于存储扫描数据
	MOV 41H,#00H
	MOV 42H,#00H
	MOV 43H,#00H
	MOV 44H,#00H
	MOV 45H,#00H
	MOV 46H,#00H
	MOV 47H,#00H
	ret
;====================================================================
SCANNING:
	MOV R1,#0FEH  ;R1存储单元中赋值十六进制数0FE转化为二进制即11111110
        MOV R0,#40H   ;R0存储单元中存放存储扫描数据空间第一个存储单元值
        MOV R3,#01	;R3中值为换线器控制值，同时R3为循环控制值
	MOV R2,#00H	;值是否变动判断条件
	LCALL SUBWORK	;调用子程序WL
	RET
SUBWORK:	
	MOV P3,#0FFH	;P3口接扫描电路列总线，P3口赋值十六进制FF，即P3口全高电平
	MOV A,R3	
	DEC A
	MOV P2,A	;换线器赋值
	
        MOV A,R1	
 	MOV P1,A	;将R1中的11111110发送至P1口，即第一行线为第电平，其他行为高电平
	LCALL DELAY100US 	;延迟一段时间
	MOV A,P3	;检测P3口值
	CPL A		;将P3口值取反
	
	MOV B,@R0
	XRL A,B
	JNZ CSCAN
	MOV R2,#09
CSCAN:	
	MOV @R0,A	;将P3口值放入存储单元R0中值所指向的RAM单元
       	MOV A,R1	
	RL A		
	MOV R1,A	;将R1中0值循环左移
	INC R0		;指向下一个RAM存储单元
	INC R3		;R3中值加1
	
	CJNE R3,#09,SUBWORK	;将R3中值和9比较，若不等于9，则循环至WL；若等于9，则返回
        RET
	
DELAY100US:
       MOV R7,#4
SUBDELAY:   
       MOV R6,#25
       DJNZ R6,$
       DJNZ R7,SUBDELAY
       RET
       
       
       
   END
